- hosts: all
  become: yes
  become_method: sudo
  pre_tasks:
    - name: Install required roles
      ansible.builtin.shell: ansible-galaxy role install lucascbeyeler.baseline
      ignore_errors: yes

  roles:
    - role: lucascbeyeler.baseline
      hostname: pikachu
      domain: johto.com
      timezone: America/Sao_Paulo
      enable_hushlogin:
      ssh_port: 8080

  ansible_env:
    ANSIBLE_ROLES_PATH: /etc/ansible/roles
