---
- name: Config IP
  gather_facts: false
  hosts: all
  tasks:
    - name: Run basic PowerShell script
      ansible.windows.win_powershell:
        script: |
          New-NetIPAddress -InterfaceIndex “14” -IPAddress '{{ var_ip }}' -PrefixLength 24 -DefaultGateway '{{ var_gw }}'
