---
- name: Config IP
  hosts: all
  collections:
    - community.windows
  gather_facts: false
  tasks:
    - name: Run basic PowerShell script
      ansible.windows.win_powershell:
        script: |
          New-NetIPAddress -InterfaceIndex “14” -IPAddress '10.8.156.250' -PrefixLength 24 -DefaultGateway '10.8.156.1'
