---
- name: Config IP
  hosts: all
  collections:
    - ansible.windows
  gather_facts: false
  tasks:
    - name: Run basic PowerShell script
      win_powershell:
        script: |
          New-NetIPAddress -InterfaceIndex “18” -IPAddress 10.8.156.250 -PrefixLength 24 -DefaultGateway 10.8.156.1
