---     
- name: Copy file from poll to remote
  hosts: 10.8.230.59
  tasks:
    - name: Copy file to a remote
      ansible.builtin.fetch:
        src: "{{ poll }}"
        dest: "/root/file/"

- name: Transfer file from remote to target
  hosts: all
  tasks:
    - name: Copy file from temporary directory
      ansible.builtin.copy:
        src: "/root/file/10.8.230.59/{{poll}}"
        dest: "{{ dst }}"
