--- 
- hosts: all
  gather_facts: false 
  connection: network_cli
  vars:
    ansible_become: true
    ansible_become_method: enable
    ansible_become_password: 'P@ssw0rd123'
    ansible_user: 'admin'
    ansible_password: 'P@ssw0rd123'
    ansible_network_os: dellemc.os10.os10
    os10_vlan:
        vlan 237 : 
          description: "vlan engginer"
          tagged_members:
            - port: ethernet 1/1/33
              state: present
            - port: ethernet 1/1/34
              state: present
          state: present
  collections: 
    - dellemc.os10
  roles:
    - os10_vlan
