--- 
- hosts: all
  gather_facts: false 
  connection: network_cli
  vars:
    ansible_network_os: dellemc.os10.os10
    ansible_user: admin
    ansible_password: 'P@ssw0rd123'
  collections: 
    - dellemc.os10 
  tasks: 
  - name: "create Vlan"
    os10_vlan:
      vlan 200:
        description: "Blue"
        tagged_members:
            - port: ethernet 1/1/29
              state: present
            - port: ethernet 1/1/30
              state: present
          
  
