--- 
- hosts: all
  gather_facts: false 
  connection: network_cli
  vars:
    ansible_network_os: dellemc.os10.os10
    ansible_user: admin
    ansible_password: 'P@ssw0rd123'
  collections: 
    - dellemc.os10 
    
  tasks: 
  - name: "Set hostname and configure VLAN 10" 
    os10_config: 
      commands:
        - hostname {{hostname}} 
        - interface vlan 10 
    register: set_hostname_vlan 
    
  - debug: var=set_hostname_vlan
