---
- hosts: all
  - name: Get all Falcon sensor options
  crowdstrike.falcon.falconctl_info:

  - name: Get a subset of Falcon sensor options
    crowdstike.falcon.falconctl_info:
      name:
        - 'cid'
        - 'aid'
        - 'tags'
