---     
- name: Copy file from poll to remote
  hosts: 10.8.230.61
  tasks:
    - name: Copy file to a remote
      ansible.builtin.fetch:
        src: "{{ poll }}"
        dest: "/root/file/"
        
- name: Copy file from temporary directory
  hosts: all:!10.8.230.61
  vars:
    ansible_user: "administrator"
    ansible_password: "P@ssw0rd"
    ansible_port: 22
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_ssh_retries: 3
    ansible_shell_type: powershell
    ansible_become_method: runas
    ansible_become_user: "{{ ansible_user }}"
    ansible_pool: "{{pool}}"
  tasks:
    - name: Copy file from temporary directory
      ansible.windows.win_copy:
        src: "/root/file/10.8.230.61/{{ansible_poll}}"
        dest: "{{ dst }}"
