---
- name: Patch Ubuntu Servers
  hosts: all
  become: yes  # This enables privilege escalation to perform tasks as root
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

    - name: Upgrade packages
      apt:
        upgrade: safe
      become: yes
