---
- name: Deploy SSL certificates on Zimbra servers
  hosts: all
  become: yes

  vars:
    cert_files:
      - STAR_polri_go_id.crt
      - SectigoRSADomainValidationSecureServerCA.crt
      - USERTrustRSAAAACA.crt
      - AAACertificateServices.crt
      - polri.key
    cert_source_dir: /home/adminserver
    cert_dest_dir: /opt/zimbra/ssl/sslcerts
    combined_cert: /tmp/commercial_ca.crt
    commercial_cert: /tmp/commercial.crt

  tasks:
    - name: Create certificate destination directory if not exists
      file:
        path: "{{ cert_dest_dir }}"
        state: directory
        owner: zimbra
        group: zimbra
        mode: '0755'

    - name: Copy certificate files to Zimbra server
      copy:
        src: "{{ cert_source_dir }}/{{ item }}"
        dest: "{{ cert_dest_dir }}/{{ item }}"
        owner: zimbra
        group: zimbra
        mode: '0644'
      loop: "{{ cert_files }}"

    - name: Combine certificates into one file
      shell: |
        cat {{ cert_dest_dir }}/AAACertificateServices.crt {{ cert_dest_dir }}/USERTrustRSAAAACA.crt {{ cert_dest_dir }}/SectigoRSADomainValidationSecureServerCA.crt > {{ combined_cert }}

    - name: Copy commercial certificate
      copy:
        src: "{{ cert_source_dir }}/STAR_polri_go_id.crt"
        dest: "{{ commercial_cert }}"
        owner: zimbra
        group: zimbra
        mode: '0644'

    - name: Copy key to the commercial directory
      copy:
        src: "{{ cert_source_dir }}/polri.key"
        dest: /opt/zimbra/ssl/zimbra/commercial/commercial.key
        owner: zimbra
        group: zimbra
        mode: '0600'

    - name: Verify the SSL certificate
      shell: |
        su - zimbra -c "/opt/zimbra/bin/zmcertmgr verifycrt comm /opt/zimbra/ssl/zimbra/commercial/commercial.key {{ commercial_cert }} {{ combined_cert }}"
      register: verify_output

    - name: Debug verification output
      debug:
        var: verify_output.stdout

    - name: Deploy the SSL certificate
      shell: |
        su - zimbra -c "/opt/zimbra/bin/zmcertmgr deploycrt comm {{ commercial_cert }} {{ combined_cert }}"
      register: deploy_output

    - name: Debug deployment output
      debug:
        var: deploy_output.stdout
        
    - name: Restart Zimbra services
      shell: su - zimbra -c "zmcontrol restart"
