- hosts: all
  gather_facts: false
  vars:
    falcon_windows_uninstall_args: "/norestart"
    falcon_windows_become_method: runas
    falcon_windows_become_user: SISTEM
  collections: 
    - crowdstrike.falcon
  roles:
    - falcon_uninstall
