- hosts: all
  tasks:
  - name: CrowdStrike Falcon | Find Windows installer in Package Cache
    ansible.windows.win_find:
      paths: C:\ProgramData\Package Cache
      patterns: WindowsSensor.exe
      recurse: yes
    register: falcon_win_sensor_cache

  - name: CrowdStrike Falcon | Remove Falcon Sensor (Windows)
    ansible.windows.win_package:
      path: "{{ falcon_win_sensor_cache.files[0].path }}"
      state: absent
      creates_service: csfalconservice
      arguments: '/uninstall /quiet {{ falcon_windows_uninstall_args }}'
