---
- hosts: all
  vars:
    become: true
    become_method: runas
    become_user: SYSTEM
    falcon_windows_uninstall_args: "/norestart"
  tasks:
    - name: CrowdStrike Falcon | Find Windows installer in Package Cache
      ansible.windows.win_find:
        paths: C:\ProgramData\Package Cache
        hidden: yes
        file_type: file
        use_regex: yes
        patterns: WindowsSensor.exe
        recurse: yes
      register: falcon_win_sensor_cache
      
    - debug: var=falcon_win_sensor_cache

    - name: CrowdStrike Falcon | Remove Falcon Sensor (Windows)
      ansible.windows.win_package:
        path: "{{ falcon_win_sensor_cache.files[0].path }}"
        state: absent
        creates_service: csfalconservice
        arguments: '/uninstall /quiet {{ falcon_windows_uninstall_args }}'
      when:
        - falcon_win_sensor_cache.files | length > 0
        - ansible_os_family == "Windows"
