---
- name: Guest Creation
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: vcenter_vars.yml
  tasks:
    - name: Clone a virtual machine
      community.vmware.vmware_guest:
        name: "{{ vm_name1 }}"
        template: "{{ template_name1 }}"
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no 
        folder: "{{ folder }}"
        datacenter: "{{ datacenter }}"
        cluster: "{{ cluster }}"
      register: vm_result

    - name: Assert that VM is created
      assert:
        that:
          - "vm_result.changed"
    - name: Poweron virtual machine
      community.vmware.vmware_guest_powerstate:
        name: "{{ vm_name1 }}"
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: False
        folder: "{{ folder }}"
        state: powered-on
